# Generated by Django 5.1.1 on 2024-09-29 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_records_missing_in_target', models.TextField(null=True)),
                ('target_records_missing_in_source', models.TextField(null=True)),
                ('descrepancies', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
